name: Deploy to EC2

on:
  push:
    branches:
      - master  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Ensure this matches your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install build tools for C++
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile C++ code
      run: |
        cd server/calculations  # Change to your C++ code directory
        g++ -o monte_carlo MonteCarlo.cpp -lm    # Compile your C++ files
        g++ -o binomial_tree BinomialTree.cpp -lm
        g++ -o black_scholes BlackScholes.cpp -lm

    - name: Add EC2 to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
      
    - name: Copy files to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem
        scp -i key.pem -r . ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/Option-Pricing/server
      

    - name: SSH into EC2 and restart Gunicorn/Nginx
      run: |
        ssh -i key.pem ec2-user@${{ secrets.EC2_IP }} << EOF
          cd /home/ec2-user/Option-Pricing/server
          source venv/bin/activate  # Activate your virtual environment if used
          pip install -r requirements.txt
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF

    - name: Cleanup SSH key
      run: rm key.pem
